const colors =   [`AliceBlue`,
`AntiqueWhite`,
`Aqua`,
`Aquamarine`,
`Azure`,
`Beige`,
`Bisque`,
`Black`,
`BlanchedAlmond`,
`Blue`,
`BlueViolet`,
`Brown`,
`BurlyWood`,
`CadetBlue`,
`Chartreuse`,
`Chocolate`,
`Coral`,
`CornflowerBlue`,
`Cornsilk`,
`Crimson`,
`Cyan`,
`DarkBlue`,
`DarkCyan`,
`DarkGoldenRod`,
`DarkGray`,
`DarkGrey`,
`DarkGreen`,
`DarkKhaki`,
`DarkMagenta`,
`DarkOliveGreen`,
`Darkorange`,
`DarkOrchid`,
`DarkRed`,
`DarkSalmon`,
`DarkSeaGreen`,
`DarkSlateBlue`,
`DarkSlateGray`,
`DarkSlateGrey`,
`DarkTurquoise`,
`DarkViolet`,
`DeepPink`,
`DeepSkyBlue`,
`DimGray`,
`DimGrey`,
`DodgerBlue`,
`FireBrick`,
`FloralWhite`,
`ForestGreen`,
`Fuchsia`,
`Gainsboro`,
`GhostWhite`,
`Gold`,
`GoldenRod`,
`Gray`,
`Grey`,
`Green`,
`GreenYellow`,
`HoneyDew`,
`HotPink`,
`IndianRed`,
`Indigo`,
`Ivory`,
`Khaki`,
`Lavender`,
`LavenderBlush`,
`LawnGreen`,
`LemonChiffon`,
`LightBlue`,
`LightCoral`,
`LightCyan`,
`LightGoldenRodYellow`,
`LightGray`,
`LightGrey`,
`LightGreen`,
`LightPink`,
`LightSalmon`,
`LightSeaGreen`,
`LightSkyBlue`,
`LightSlateGray`,
`LightSlateGrey`,
`LightSteelBlue`,
`LightYellow`,
`Lime`,
`LimeGreen`,
`Linen`,
`Magenta`,
`Maroon`,
`MediumAquaMarine`,
`MediumBlue`,
`MediumOrchid`,
`MediumPurple`,
`MediumSeaGreen`,
`MediumSlateBlue`,
`MediumSpringGreen`,
`MediumTurquoise`,
`MediumVioletRed`,
`MidnightBlue`,
`MintCream`,
`MistyRose`,
`Moccasin`,
`NavajoWhite`,
`Navy`,
`OldLace`,
`Olive`,
`OliveDrab`,
`Orange`,
`OrangeRed`,
`Orchid`,
`PaleGoldenRod`,
`PaleGreen`,
`PaleTurquoise`,
`PaleVioletRed`,
`PapayaWhip`,
`PeachPuff`,
`Peru`,
`Pink`,
`Plum`,
`PowderBlue`,
`Purple`,
`Red`,
`RosyBrown`,
`RoyalBlue`,
`SaddleBrown`,
`Salmon`,
`SandyBrown`,
`SeaGreen`,
`SeaShell`,
`Sienna`,
`Silver`,
`SkyBlue`,
`SlateBlue`,
`SlateGray`,
`SlateGrey`,
`Snow`,
`SpringGreen`,
`SteelBlue`,
`Tan`,
`Teal`,
`Thistle`,
`Tomato`,
`Turquoise`,
`Violet`,
`Wheat`,
`White`,
`WhiteSmoke`,
`Yellow`,
`YellowGreen`
]

function getRandomElement(array) {
    if (array.length === 0) {
      return undefined; // Return undefined for empty arrays
    }
    const randomIndex = Math.floor(Math.random() * array.length);
    return array[randomIndex];
}

var button;

function on_colorbutton_click(event){
    button.style.backgroundColor = getRandomElement(colors)
    button.style.width = "98%";
    button.style.height = "98%";
    setTimeout(() => {
        button.style.width = "100%";
        button.style.height = "100%";
    }, 50);
}

function on_load(event){
    button = document.getElementById("colorbutton");
    button.addEventListener("click", on_colorbutton_click);
}

window.addEventListener("load", on_load)

